[package]
name = "heatshrink-rust"
version = "0.5.0"
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dev-dependencies]
rand = "0.8"